apiVersion: v1
kind: Service
metadata:
  name: burstops-backend
  namespace: burstops
  labels:
    app: burstops-backend
spec:
  type: ClusterIP
  selector:
    app: burstops-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
